export enum ValueType {
    UnInferred = 'uninferred',
    Void = 'void',
    Null = 'null',
    Boolean = 'boolean',
    Number = 'number',
    BigInt = 'bigint',
    String = 'string',
    Object = 'object',
    Array = 'array',
    Function = 'function',
    Status = 'napi_status',
    Any = 'any',
    Undefined = 'undefined',
    Global = 'global',
    Error = 'error',
}